version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sayan   # Root password
      MYSQL_DATABASE: PersonalFinance    # Database to create
      MYSQL_USER: root            # Dedicated user
      MYSQL_PASSWORD: sayan    # User password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: finacny-backend:latest
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PersonalFinance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sayan
      SERVER_PORT: 9090

volumes:
  mysql-data:
