version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Root password
      MYSQL_DATABASE: PersonalFinance    # Database to create
      MYSQL_USER: financyuser            # Dedicated user
      MYSQL_PASSWORD: financypassword    # User password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    image: finacny-backend:latest
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PersonalFinance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: financyuser
      SPRING_DATASOURCE_PASSWORD: financypassword
      SERVER_PORT: 9090

volumes:
  mysql-data:
